name: CI

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-node@v1
      with:
        node-version: 18.x
    - uses: bufbuild/buf-setup-action@v1
    - run: yarn --frozen-lockfile
    - run: yarn test
    - name: Coveralls
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: packages/protoc-gen-nexus/coverage/lcov.info
        base-path: packages/protoc-gen-nexus

  test-e2e:
    name: E2E Test - Node.js v${{ matrix.node-version }}
    strategy:
      matrix:
        node-version: [16, 18]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: bufbuild/buf-setup-action@v1
    - run: yarn --frozen-lockfile
    - run: yarn test:e2e
