name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: yarn --frozen-lockfile
    - run: yarn test
    - name: Coveralls
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: packages/protoc-gen-nexus/coverage/lcov.info
        base-path: packages/protoc-gen-nexus

  lint:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: yarn --frozen-lockfile
    - run: yarn lint
      env:
        NODE_OPTIONS: "--max_old_space_size=4096"
    - run: yarn format
    - name: check generated code is up to date
      run: git diff --exit-code

  test-e2e:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - uses: bufbuild/buf-setup-action@v1
    - run: yarn --frozen-lockfile
    - run: yarn test:e2e
