name: Lint

on: [pull_request]

jobs:
  lint:
    name: Lint and Format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true
    - uses: pnpm/action-setup@v2
      with:
        version: 7
    - uses: actions/setup-node@v1
      with:
        node-version: 18.x
        cache: 'pnpm'
    - run: pnpm install  --frozen-lockfile
    - run: pnpm lint
    - run: pnpm format
    - name: check code is up to date
      run: git diff --exit-code
