name: Lint

on: [pull_request]

jobs:
  lint:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true
    - uses: actions/setup-node@v1
      with:
        node-version: 18.x
    - run: yarn --frozen-lockfile
    - run: yarn lint
      env:
        NODE_OPTIONS: "--max_old_space_size=8192"
    - run: yarn format
    - name: check code is up to date
      run: git diff --exit-code
